# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c528202194d06b95f6f482e6c32440c32e5d5ec06c9109b2577c1e399108f6761d639fe889bdcc4b78f45a3f3b52e7e19dc148771f2fe74daa40049d6799638

test:
  secret_key_base: 25c3e496a6260691461f121724ce84d366487f3fb892a014d49498429d7598e370086ef67f916943ed531f2d9866121bf61db0249d919093f1f504d43942c406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
